### PR TITLE
Travis deploy docs instead of having them in repo

### PR DESCRIPTION
**Pull request by kamerat**
I guess we don't want the build output in the repo, so this PR gitignores `/docs` and removes the previous folder in git and deploys it to github pages instead

### CODE REVIEW

**Comment by logan-laughery** [comment]
We may need to update .travis.yml so that the docs are deployed to github pages. Previously, they were deployed via a local build followed by pushing the doc folder up.

**Comment by kamerat** [comment]
I'm not too experienced in travis, but I can try to add a basic setup to this PR

**Comment by kamerat** [comment]
With the following 3 commits, deploying to gh-pages via travis now works on my fork.
In order to get it working on here, you have to provide a new environment variable for travis; `GITHUB_TOKEN` with the value being a newly generated token with repo access only.

Also, you have to create a new branch named `docs` that will hold the generated docs.
In the repo settings, you have to change the github pages source to be the branch `docs` with folder `/(root)`

**Review by logan-laughery — APPROVED** [review]
Awesome work!  I should have everything configured as it needs to be.  This is definitely a huge improvement compared to the way the docs were previously deployed.

**Pull request merged**
